# Generated by Django 4.2.10 on 2024-03-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            (0, "Principal Investigator"),
                            (1, "Researchers"),
                            (2, "PhD. Candidates"),
                            (3, "Master’s Students"),
                            (4, "Undergraduate Students"),
                        ],
                        default="Secret",
                        max_length=100,
                    ),
                ),
                ("education", models.TextField(max_length=200)),
            ],
        ),
    ]
