# Generated by Django 4.2.10 on 2024-03-10 14:43

from django.db import migrations, models
import people.models


class Migration(migrations.Migration):
    dependencies = [
        ("people", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=people.models.user_directory_path,
                verbose_name="photo",
            ),
        ),
    ]
