# Generated by Django 4.2.10 on 2024-03-10 10:36

from django.db import migrations, models
import publication.models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=publication.models.user_directory_path,
                verbose_name="preview",
            ),
        ),
    ]
