# Generated by Django 4.2.10 on 2024-03-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publication", "0003_publication_pub_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="publication",
            name="pub_year",
            field=models.PositiveIntegerField(default=1999),
        ),
    ]
