# Generated by Django 4.2.10 on 2024-03-11 06:12

from django.db import migrations, models
import research.models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="research",
            name="icon",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=research.models.user_directory_path,
                verbose_name="icon",
            ),
        ),
    ]
